backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 6;
shadow-opacity = 0.35;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

corner-radius = 2;

blur:
{
  method = "dual_kawase";
  strength = 2;
};

opacity-rule = [
    "85:class_g = 'vesktop'",
];
